# Format Python
[tool.black]
line-length = 80
target-version = ['py37', 'py38', 'py39', 'py310']
include = '(\.pyi?$|\.spec$)'
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | buildozer\.spec
)
'''

# Sort imports
# Settings to fit Black formatting
# Taken from https://github.com/timothycrosley/isort/issues/694
[tool.isort]
line_length = 80
include_trailing_comma = true
multi_line_output = 3
use_parentheses = true
force_grid_wrap = 0
ensure_newline_before_comments = true
known_third_party = ["setuptools", "kivy", "requests", "PIL", "android", "jnius", "watchdog", "sphinx", "docutils", "autoapi", "unidecode"]
